services:
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend/prisma:/app/prisma
      - ./frontend/src:/app/src
      - ./frontend/next-env.d.ts:/app/next-env.d.ts
      - ./frontend/next.config.mjs:/app/next.config.mjs
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/package.json:/app/package.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
    ports:
      - "3000:3000"
    networks:
      - dev
    env_file:
      - .env

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - dev

networks:
  dev:
