import { Header } from "@/ui/admin/components/header/Header";
import "./layout.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="layout-admin">
      <Header />
      {children}
    </div>
  );
}
